// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgOkgsLXaa4ga-co5FGaVTb9fkroWpg3M',
    appId: '1:826622552589:web:c3c37ae751d231d5eb4344',
    messagingSenderId: '826622552589',
    projectId: 'groupting-aebab',
    authDomain: 'groupting-aebab.firebaseapp.com',
    databaseURL: 'https://groupting-aebab-default-rtdb.firebaseio.com',
    storageBucket: 'groupting-aebab.firebasestorage.app',
    measurementId: 'G-82GYK98H49',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGzgBkOmqsh3Su_lHarO3yufDpJXCSdQQ',
    appId: '1:826622552589:android:b8cd6195c9eca66aeb4344',
    messagingSenderId: '826622552589',
    projectId: 'groupting-aebab',
    databaseURL: 'https://groupting-aebab-default-rtdb.firebaseio.com',
    storageBucket: 'groupting-aebab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHgXnkh3FYEqy9LOwnt6mdBclDhX7zOLc',
    appId: '1:826622552589:ios:8edb281a853c4f31eb4344',
    messagingSenderId: '826622552589',
    projectId: 'groupting-aebab',
    databaseURL: 'https://groupting-aebab-default-rtdb.firebaseio.com',
    storageBucket: 'groupting-aebab.firebasestorage.app',
    iosBundleId: 'com.rlgus16.groupting',
  );

}